//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.23 at 01:41:44 AM CET 
//

package de.minecrawler.IR1.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "TEXT")
public class Text {

    @XmlAttribute(name = "TYPE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String type;

    @XmlElement(name = "BODY", required = false)
    protected String body;

    @XmlElement(name = "TITLE", required = false)
    protected String title;

    @XmlElement(name = "AUTHOR", required = false)
    protected String author;

    @XmlElement(name = "DATELINE", required = false)
    protected String dateline;

    public String getType() {
        return type;
    }

    public void setTYPE(String value) {
        this.type = value;
    }

    public String getAuthor() {
        return author;
    }
    public String getBody() {
        return body;
    }
    public String getDateline() {
        return dateline;
    }
    public String getTitle() {
        return title;
    }

}
