//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.23 at 01:41:44 AM CET 
//

package de.minecrawler.IR1.data;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"reuters"})
@XmlRootElement(name = "LEWIS")
public class XMLDocumentList implements Iterable<XMLDocument> {

    @XmlElement(name = "REUTERS", required = true)
    private List<XMLDocument> reuters = new ArrayList<XMLDocument>();

    protected XMLDocumentList() {
    }

    public XMLDocumentList(List<XMLDocument> list) {
        this.reuters = list;
    }

    public List<XMLDocument> getDocuments() {
        return this.reuters;
    }

    public Iterator<XMLDocument> iterator() {
        return this.reuters.iterator();
    }

}
